[package]
name = "frontend_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.2"
actix-web = "4.2.1"
futures-util = "0.3.24"
serde = "1.0.145"
serde_yaml = "0.9.13"
